import Link from "next/link"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
     
      <body>
      <nav>
      <Link href="/" > Home </Link>
      <Link href="./blog" > Blog </Link>
      <Link href="./about" > About </Link>
      <Link href="./products" > Product </Link>
      </nav>
        <header style={{
          backgroundColor: "lightblue",
          padding:"1rem"
        }}>
          <p>Header</p>

        </header>
        {children}

        <footer style={{
          backgroundColor: "goldenrod",
          padding: "1rem"
        }}>
          <p>Footer</p>
        </footer>
        </body>
    </html>
  )
}
